debug: debug_resp
interactsh_server: null
output_file: null
proxy: {}
retries: 0
templates:
- .\template\demo template\Demo-13-5-2022\CVE-2021-44228.yaml
thread: null
timeout: 10
url:
- http://103.90.225.135:8001/
verbose: false
