debug: null
interactsh_server: null
output_file: null
proxy:
  http: http://127.0.0.1:8080
  https: http://127.0.0.1:8080
retries: 0
templates:
- .\template\demo template\addBodyJsonAndQueryToCVE44228.yaml
thread: null
timeout: 5
url:
- http://127.0.0.1/
verbose: false
