debug: null
interactsh_server: null
output_file: null
proxy: {}
retries: 0
templates:
- template\demo template\TimebasedSQLInjection-Shoes-Shop.yaml
thread: null
timeout: 5
url:
- http://103.90.225.135:8001
verbose: false
