debug: null
interactsh_server: null
output_file: null
proxy:
  http: http://127.0.0.1:8080
  https: http://127.0.0.1:8080
retries: 0
templates:
- template/wordpress/CVE-2022-27849.yaml
thread: null
timeout: 10
url:
- https://danhdcse140043.000webhostapp.com/
verbose: false
