debug: null
interactsh_server: null
output_file: null
proxy:
  http: http://127.0.0.1:8080
  https: http://127.0.0.1:8080
retries: 0
templates:
- template\demo template\Demo-13-5-2022\CVE-2021-44228.yaml
thread: null
timeout: 10
url:
- ftp://www.facebook.com
- ftp://stackoverflow.com/credential/abcxyz/?abc=xyz
- ftp://103.90.227.30:81/
- ftp://192.168.1.1
- ftp://127.0.0.1/
- ftp://howkteam.vn
- ftp://domainbayba.com
- http://103.90.225.135:8001
verbose: false
