debug: debug
interactsh_server: null
output_file: null
proxy: {}
retries: 0
templates:
- .\template\wordpress\CVE-2019-14205.yaml
- .\template\wordpress\CVE-2021-24495.yaml
- .\template\wordpress\CVE-2022-0288.yaml
- .\template\wordpress\CVE-2022-0653.yaml
- .\template\wordpress\CVE-2022-1119.yaml
- .\template\wordpress\CVE-2022-27849.yaml
thread: null
timeout: 10
url:
- http://103.90.225.135:8001/
verbose: false
